### PR TITLE
Add Python 3.x support

### LINKED ISSUE #9: Support for Python 3
This is currently blocked by the dependency on M2Crypto. Reading the discussion in martinpaljak/M2Crypto#23 is not very encouraging. M2Crypto seems rather poorly maintained in general.

Poking around the source a bit, my impression is that M2Crypto could be replaced with pyopenssl. Can someone more familiar with the project confirm or deny?

### PR DESCRIPTION
**Pull request by moreati**
This builds on #18 and fixes #9

### CODE REVIEW

**Comment by dainnilsson** [comment]
@moreati - What's the status of this PR? I'd like to make an effort to get everything ready and do a new release of the project soon-ish. Let me know if you want me to take over (if so, also let me know what your plans were so I don't miss anything).

**Comment by moreati** [comment]
Sorry, I got stuck finding a good cleanup of all the string types and then other projects took over. I've just pushed a snapshot of my working copy to https://github.com/moreati/python-u2flib-server/tree/python3.x-stringmess for reference. I'll try to work more on this PR this week. I can't promise anything though. Feel free to take over.

**Comment by dainnilsson** [comment]
Alright, I took a stab at it: 49930e539deeede13fcc512feaf88bc414080a46
The PyPy build is still failing, but it seems this is an issue with TravisCI using an old version of PyPy: travis-ci/travis-ci/issues/4756
Anyway, I'd appreciate a second pair of eyes on these changes!

**Comment by moreati** [comment]
> Anyway, I'd appreciate a second pair of eyes on these changes!

Thank you, and sorry for dragging my heels. Having a look now, I'll add comments in-line.

**Comment by moreati** [comment]
@dainnilsson I'm done, I consider this ready for merge. Thank you again for pulling me out that quagmire of string types.

**Comment by dainnilsson** [comment]
Huge thanks for all the work you've put into this!

**Comment by gavinwahl** [comment]
Yay!

**Pull request merged**
