### PR TITLE
Move soft_u2f_v2 into installed package and update test imports

### PR DESCRIPTION
**Pull request by systemsoverload**
It would be very nice if the SoftU2FDevice class were part of the installed library to support writing unit tests without having to vendor that file.

### CODE REVIEW

**Comment by herrjemand** [comment]
@systemsoverload I don't see how does soft_u2f should be a part of python-u2flib-server. python-u2flib-server is a library for server side check and challenge generation. There is not reason for software implementation of U2F token to be in a server module.

**Comment by systemsoverload** [comment]
@herrjemand I don't necessarily disagree however it is already being implemented as part of this library. If it were a separate installable package that would also solve the problem of having to vendor this file in order to write unit tests in applications that use this package, but Im not sure that's what you were advocating either.

**Comment by herrjemand** [comment]
@systemsoverload I am simply saying that software implementation of U2F token, has no need to be in server module.

There more to it. You can not simply take `soft_u2f_v2.py`, and move it to `u2flib_server` folder.

 - The private key is not unique. You need to implement unique private key generation, or your soft solution will generate same key handle for every registration.
 - Certificate need to be unique as well.

Current `soft_u2f_v2.py` solution is only intended for one single test, and not complaint with specs.

**Comment by phillbaker** [comment]
If it helps, it looks like a very similar class is available in `python-u2flib-host`: https://github.com/Yubico/python-u2flib-host/blob/1e1bcb91ddb52f39ffd549a8dc077cae80ba35b1/u2flib_host/soft.py

**Comment by dainnilsson** [comment]
Closing this issue now. The soft U2F implementation here is very rudimentary and is only ment to be used for the tests in this project.

**Pull request closed without merging**
