### PR TITLE
Improved examples readability, and fixed few bugs

### PR DESCRIPTION
**Pull request by herrjemand**
Made yubiauth_server.py executable

u2f_server.py
- Replaced self.facet with self.app_id
- Created new variable self.facets = [self.app_id]
- Replaced all [self.facet] with self.facets for convinience
- Code readability
- Renamed `c` and `t`, to `counter` and `touch`.
- Booleaned `touch` as u2f_lib returns binary for touch, and JSON does not support binary.

yubiauth_server.py
- Replaced self.origin with self.app_id
- Created new variable self.facets = [self.app_id]
- Replaced all [self.origin] with self.facets for convinience
- Code readability
- Renamed `c` and `t`, to `counter` and `touch`.
- Booleaned `touch` as u2f_lib returns binary for touch, and JSON does not support binary.

### CODE REVIEW

**Comment by dainnilsson** [comment]
Hi! Looks pretty good to me, just a few minor things:

1. The subject mentions "a few bugs", but I'm not sure I see any bug fixes. Can you elaborate on what you consider a bug? I just want to make sure I'm not missing anything!
2. I'm not entirely sure about the change of touch to a boolean. The specification states: "A user presence byte [1 byte]. Bit 0 is set to 1, which means that user presence was verified. (This version of the protocol doesn't specify a way to request authentication responses without requiring user presence.) A different value of Bit 0, as well as Bits 1 through 7, are reserved for future use. The values of Bit 1 through 7 should be 0". So the value is defined as a byte, but currently can only have a single value (1, since there is no way to perform an operation without requiring user presence). In that sense it actually makes more sense to do an equality check in the library itself, and raise an exception on any other value. However, the value might be changed in a future specification. For example, bits 1-7 might indicate additional information about the action performed by the user.
As these are just example files it may be overthinking it a bit here. It really doesn't matter what is returned, since it's for demonstration purposes only. Basically, if you want to return a boolean here, I think the better expression might be bool(touch & 1), ie. True iff bit 0 is set.

**Comment by dainnilsson** [comment]
Hmm, I just looked over the code and I think I misunderstood you initially. Now I think I've got the answer to both 1 and 2. I thought you changed the type of touch from an int to a bool, but I'm now guessing you were actually changing it from the python 3 "bytes" type to a bool. The bug being that the bytes value cannot be serialized. On python 2 this value is actually an int, so the JSON serialization works just fine. I'm guessing the examples just weren't properly tested on python 3. Is this what you were referring to? If so, I think the byte should be converted into an int using byte2int from the u2flib_server.yubicommon.compat module, and then either be returned as-is, or as a bool by checking bit 0. Would you agree with that?

**Comment by herrjemand** [comment]
Hello @dainnilsson!

Yes. You understand correctly.

In yubicommon 

```python
def byte2int(i):
    if _PY2:
        return ord(i)
    return i
```

Python3 supports ord as well, so we can just remove Python2 checker

```python
def byte2int(i):
    return ord(i)
```

And then in python-u2flib-server, in RawAuthenticationResponse, we can simply
```
self.user_presence = byte2int(data[0:1]) << 7
```

**Comment by dainnilsson** [comment]
Sorry, brainfart. I'm going on vacation tomorrow and it seems my brain is
shutting down ahead of time. Since the type of this is str/bytes of length
1 you don't want to call byte2int, you want ord as you say. The byte2int
function is for when you for example iterate over a string of bytes, which
yields ints on Python 3 and single char strings on Python 2.

**Comment by herrjemand** [comment]
@dainnilsson except in python3 it returns byte value, and you are expecting int's.

**Comment by herrjemand** [comment]
@dainnilsson what about just use bytearray?

```python
self.user_presence = bytearray(data[0:1])  << 7
```

**Comment by dainnilsson** [comment]
Uh, I'm just going to keep quiet until I get a chance to sit down with the
code and can actually verify my claims :) I'll try to check later.
Also: Thanks, and good luck with your talk! Let me know if it becomes
available online!

**Comment by herrjemand** [comment]
@dainnilsson thanks. You have a good holiday. *)

**Comment by dainnilsson** [comment]
Ok, at a computer now. The value of the (now renamed) touch variable, as returned by verify_authenticate(), is 'str' on Python 2, and 'bytes' on Python 3. The length of the variable is 1 in either case. It would probably make more sense to instead return an int, but that change would break backwards compatibility.

My suggestion was to leave the return type as-is for now, and instead call ord() on the returned value to turn it into an int (on both Python 2 and 3). Then either serialize that int in the JSON response, or go one step further, and convert it into a boolean:

```python
counter, touch = verify_authenticate(devices, challenge, data, self.facets)
touch = ord(touch)  # Now we have an int, works on both Python 2 and 3.

return json.dumps({
    'touch': touch,  # alternatively: 'touch': bool(touch & 1)
    ...
```

Does that make more sense?

**Comment by herrjemand** [comment]
@dainnilsson yea. It does.

Do we want to do any changes on the library level?

**Comment by dainnilsson** [comment]
Closing this now, as I don't think it applies to the current codebase. Feel free to open a new PR if there are things you'd still like to see changed.

**Pull request closed without merging**
